// Re-export shared types and extend for frontend-only types
export type {
  ApiResponse,
  PaginatedResponse,
  User,
  UserRole,
  AuthTokens,
  LoginCredentials,
  RegisterPayload,
  Job,
  JobListItem,
  JobStatus,
  ListJobsParams,
  Applicant,
  CloudinaryFile,
  DashboardAnalytics,
  PipelineStatusItem,
  HiresPerMonthItem,
  CandidateProfile,
  CandidateExperience,
  CandidateEducation,
  UpdateCandidateProfilePayload,
  Application,
  ApplicationStage,
  ActivityNote,
  ActivityTag,
  ActivityCall,
  TimelineItem,
  Project,
  CandidateListItem,
} from '@ats-saas/shared';
